### ISSUE TITLE
MGP-STR在中文效果如何？

### ISSUE THREAD

**Issue by zhunge** [AlibabaResearch/AdvancedLiterateMachinery#1]

**Comment by dcfucheng** [comment]
Hi，感谢对我们工作的关注，这是个很棒的问题。在后续的工作中，我们的确也在积极的验证MGP-STR在中文数据集上的效果。我们在[中文文字识别数据集](https://github.com/FudanVI/benchmarking-chinese-text-recognition)上进行了简单的验证，MGP-STR 在scene train数据上finetune后，scene test集Acc约66.47，符合预期。
