### ISSUE TITLE
In VGT, Is it possible on different language?

### ISSUE THREAD

**Issue by yellowjs0304** [AlibabaResearch/AdvancedLiterateMachinery#102]
Hi, Thanks for sharing nice work. 
If I want to use this model in a different language, like Japanese or Korean... What should I do? 
Am I just replacing the token embedding which made with different Bert model? (I think the pre-trained GiT is based on English)
Can I use this model in new language just fine-tuning VGT with new dataset?

**Comment by youseon-jang** [comment]
@yellowjs0304  Hi! Did you try? Can you share the result?
