### ISSUE TITLE
Links to pretrained weights

### ISSUE THREAD

**Issue by SeanBE** [AlibabaResearch/AdvancedLiterateMachinery#11]
Excited to test this TSR approach. Looks like the links to the pretrained weights are missing?

**Comment by BrownXing** [comment]
Links of model weights are updated at the README.md now. Thank you for reminding us!

**Comment by BrownXing** [comment]
If you would use the `ckpt_wireless` for inference, please add --upper_left argument to the demo_wireless.sh scripts. Since this model is trained on a different image preprocess pipeline with other checkpoints. The update of code in the repository may have some delay :)

**Comment by BrownXing** [comment]
If you would use the `ckpt_wireless` for inference, please add `--upper_left` argument to the `demo_wireless.sh` scripts. Since this model is trained on a different image preprocess pipeline with other checkpoints. The update of code in the repository may have some delay :)

**Comment by SeanBE** [comment]
Thank you :) Will give it a spin this week
