### ISSUE TITLE
cuda11以上是否可以？

### ISSUE THREAD

**Issue by yangguangjie** [AlibabaResearch/AdvancedLiterateMachinery#12]
您好， 我看您说用DLA backbone，推荐cuda10.1，请问cuda11以上版本是否可以？

**Comment by BrownXing** [comment]
可以的，采用DCNv2支持的CUDA版本即可，具体可以参考DCNv2的仓库：https://github.com/jinfagang/DCNv2_latest

**Comment by yangguangjie** [comment]
好的，非常感谢

**Comment by yangguangjie** [comment]
您好。在trian_wireless.sh中python main.py ctdet_mid  。而train_factory = {
  'ctdet': CtdetTrainer,
  'ctdet_small': CtdetTrainer
}没有ctdet_mid。请问要怎么修改

**Comment by BrownXing** [comment]
您好，请将LORE-TSR/src/lib/trains/train_factory.py中的train_factory定义修改为：
train_factory = {
  'ctdet': CtdetTrainer,
  'ctdet_mid': CtdetTrainer,
  'ctdet_small': CtdetTrainer
}
