### ISSUE TITLE
About RVL_CDIP pretrain data

### ISSUE THREAD

**Issue by GeorgeLuImmortal** [AlibabaResearch/AdvancedLiterateMachinery#137]
It seems the RVL_CDIP  ocr_data is not completed, only have 60236 json files while the whole datasets include more than 400K images?

**Comment by luochuwei** [comment]
> It seems the RVL_CDIP ocr_data is not completed, only have 60236 json files while the whole datasets include more than 400K images?

We sampled a portion of data from the RVL-CDIP dataset for the generation of instructions, instead of using all the RVL-CDIP data.

**Comment by GeorgeLuImmortal** [comment]
Thanks for the reply, and it looks like some OCR results are missing, like "No such file or directory: '...Layout-Instruction-Data/LayoutLLM_data/pretrain_data/ocr_results/RVL_CDIP/classification-RVL_CDIP--memo-img-imagesz-z-z-n-zzn55f00-0060122690.png.json'", could you please check this? Thanks.

**Comment by luochuwei** [comment]
> Thanks for the reply, and it looks like some OCR results are missing, like "No such file or directory: '...Layout-Instruction-Data/LayoutLLM_data/pretrain_data/ocr_results/RVL_CDIP/classification-RVL_CDIP--memo-img-imagesz-z-z-n-zzn55f00-0060122690.png.json'".
> 
> About 55719 out of 116K ddd sft data has corresponding OCR results, could you please check this, thanks.

![image](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/9798458/c2c9fca2-dddc-4179-a6f1-ec8e28975ba8)

it seems you delete the second "archive".
plz keep the second "archive"

**Comment by GeorgeLuImmortal** [comment]
My bad, thanks for pointing this out.
