### ISSUE TITLE
LORE-TSR使用标注格式

### ISSUE THREAD

**Issue by winterYANGWT** [AlibabaResearch/AdvancedLiterateMachinery#14]
您好，我想测试LORE-TSR在PubTabNet，SciTSR和WTW数据集上的性能，但这些数据集提供的标注格式都不同。PubTabNet为jsonl，SciTSR为chunk的structure，WTW为xml。请问我是否需要给出统一的标注类型，且标注的格式为？

**Comment by BrownXing** [comment]
请参考仓库中提供关于数据集的说明和标注样例文件，统一把不同形式的标注转换为COCO数据集的形式。
