### ISSUE TITLE
training schedule of LayoutLLM

### ISSUE THREAD

**Issue by jpWang** [AlibabaResearch/AdvancedLiterateMachinery#142]
Hi,
thanks for the great work LayoutLLM~ Congratulations!
And I just want to ask that, in the appendix of the paper, it said that "the batch size is 32 for each GPU" in pre-training and "the batch size is 8 for each GPU" in fine-tuning:
![image](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/52776462/93ae625a-6480-48f6-8f85-5b9dd92104be)
So what and how many gpus are you using? Like **8xA100-80G?**  So it results in the **pre-training** batch size as **32x8=256** and the **fine-tuning** batch size as **8x8=64**?
Looking forward to your reply~And thanks again. @luochuwei

**Comment by luochuwei** [comment]
> Hi, thanks for the great work LayoutLLM~ Congratulations! And I just want to ask that, in the appendix of the paper, it said that "the batch size is 32 for each GPU" in pre-training and "the batch size is 8 for each GPU" in fine-tuning: ![image](https://private-user-images.githubusercontent.com/52776462/331929023-93ae625a-6480-48f6-8f85-5b9dd92104be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTAwOTUsIm5iZiI6MTcxNjE4OTc5NSwicGF0aCI6Ii81Mjc3NjQ2Mi8zMzE5MjkwMjMtOTNhZTYyNWEtNjQ4MC00OGY2LThmODUtNWI5ZGQ5MjEwNGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNzExNzEzNDk0ZDQ4MmYxMDI5Nzk3MGIxOTQwM2M1MzNmNWM0YzhjZDJiNzA2NTk1NDcxMmIzZWVkMzA2OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zbQA6u-3pw4MNHZexyQ7NBnKyvjMu-ypJu1znqNEU0E) So what and how many gpus are you using? Like **8xA100-80G?** So it results in the **pre-training** batch size as **32x8=256** and the **fine-tuning** batch size as **8x8=64**? Looking forward to your reply~And thanks again. @luochuwei

Yes, you're right
