### ISSUE TITLE
Loss收敛问题

### ISSUE THREAD

**Issue by ganggang233** [AlibabaResearch/AdvancedLiterateMachinery#16]
请教一下 LORE 训练自己的数据集时，hm_loss, wh_loss, ax_loss, sax_loss 分别收敛到多少会获得一个比较好的解析效果？另外对于非readme提到的数据集，除了max_objs,max_pairs与max_cors这三个参数，还有什么参数需要修改的？
       非常期待您的回复！

**Comment by BrownXing** [comment]
hi, usually, the hm_loss, ax_loss and sax_loss are around 0.1, 0.15 and 0.15 for most dataset. the wh_loss may vary on different datasets
