### ISSUE TITLE
提供的coco数据中logic_axis和wtw原始数据标注中startcol、endcol不一致

### ISSUE THREAD

**Issue by YinongMao** [AlibabaResearch/AdvancedLiterateMachinery#17]
logic_axis是怎么转换的呢，和wtw原始的xml标注对比了一下，差别很大

**Comment by BrownXing** [comment]
xml转换json参考：https://github.com/wangwen-whu/WTW-Dataset。我们采用的是Parsing Table Structures in the Wild作者提供的标注。

**Comment by YinongMao** [comment]
我是从 [](https://tianchi.aliyun.com/dataset/108587) 这个地址下载的wtw标注和图像，这个地址就是[](https://github.com/wangwen-whu/WTW-Dataset) 项目提供的呀，我这里对比了一下logic_axis和xml里的startcol startrow并不一致，想知道这个logic_axis是怎么计算的？另外，WTW-Dataset项目里，xmltococo的代码也没有logic_axis的计算方法

**Comment by YinongMao** [comment]
我是从https://tianchi.aliyun.com/dataset/108587下载的wtw标注和图像，这个地址就是https://github.com/wangwen-whu/WTW-Dataset项目提供的，我这里对比了一下logic_axis和xml里的startcol startrow并不一致，想知道这个logic_axis是怎么计算的？另外，WTW-Dataset项目里，xmltococo的代码也没有logic_axis的计算方法

**Comment by yangy996** [comment]
大佬，这个logic_axis中的四个值代表什么意思呀，没看懂？

**Comment by Cassieyy** [comment]
> 大佬，这个logic_axis中的四个值代表什么意思呀，没看懂？

尝试替大佬回答一下，WTW数据集上logic_axis是col_start, col_end, row_start, row_end；其他logic_axis是row_start, row_end, col_start, col_end.（比如占第1行，占1-2列的cell，它的logic_axis就应该是[0, 0, 0, 1]）如果你是retrain的话，可以按照你用的哪个数据集的权重上述选其一。如果是finetune的话，可以分别按照上述样式组织。

**Comment by mengdongwei** [comment]
> > 大佬，这个logic_axis中的四个值代表什么意思呀，没看懂？
> 
> 尝试替大佬回答一下，WTW数据集上logic_axis是col_start, col_end, row_start, row_end；其他logic_axis是row_start, row_end, col_start, col_end.（比如占第1行，占1-2列的cell，它的logic_axis就应该是[0, 0, 0, 1]）如果你是retrain的话，可以按照你用的哪个数据集的权重上述选其一。如果是finetune的话，可以分别按照上述样式组织。

hi @Cassieyy  Do you have a scripts to convert datasets like Pubtabnet or Fintabnet (Jsonl/HTML) annotations to coco with logic_axis. Thanks

**Comment by mengdongwei** [comment]
> 我是从[https://tianchi.aliyun.com/dataset/108587下载的wtw标注和图像，这个地址就是https://github.com/wangwen-whu/WTW-Dataset项目提供的，我这里对比了一下logic_axis和xml里的startcol](https://tianchi.aliyun.com/dataset/108587%E4%B8%8B%E8%BD%BD%E7%9A%84wtw%E6%A0%87%E6%B3%A8%E5%92%8C%E5%9B%BE%E5%83%8F%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E5%B0%B1%E6%98%AFhttps://github.com/wangwen-whu/WTW-Dataset%E9%A1%B9%E7%9B%AE%E6%8F%90%E4%BE%9B%E7%9A%84%EF%BC%8C%E6%88%91%E8%BF%99%E9%87%8C%E5%AF%B9%E6%AF%94%E4%BA%86%E4%B8%80%E4%B8%8Blogic_axis%E5%92%8Cxml%E9%87%8C%E7%9A%84startcol) startrow并不一致，想知道这个logic_axis是怎么计算的？另外，WTW-Dataset项目里，xmltococo的代码也没有logic_axis的计算方法

Do you have a scripts to convert datasets like Pubtabnet or Fintabnet (Jsonl/HTML) annotations to coco with logic_axis. Thanks

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~
