### ISSUE TITLE
LevOCR字符集问题

### ISSUE THREAD

**Issue by cdmc-zrz** [AlibabaResearch/AdvancedLiterateMachinery#18]
你好，如果我对于字符集的检测除了大小写字母和数字以外还需要一些特殊符号例如-|~等，是不是需要重新训练整个模型，如果需要的话请问8卡A100训练ST+MJ数据集预估需要多久

**Comment by wdp-007** [comment]
你好，是的，需要重新训练或者finetune, 2卡A100大概是一周的时间，8卡估计也就2天左右
