### ISSUE TITLE
Paper & code of GeoLayoutLM?

### ISSUE THREAD

**Issue by huyhoang17** [AlibabaResearch/AdvancedLiterateMachinery#19]
Hi authors,
Thanks for the great repo!
Could you provide the paper link to Geolayoutlm?
Furthermore, I saw the code in the [current release](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/releases/tag/v1.1.0-geolayoutlm-model) is the same as the code in the main branch. Can you update this?

Thank you so much!

**Comment by luochuwei** [comment]
> Hi authors, Thanks for the great repo! Could you provide the paper link to Geolayoutlm? Furthermore, I saw the code in the [current release](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/releases/tag/v1.1.0-geolayoutlm-model) is the same as the code in the main branch. Can you update this?
> 
> Thank you so much!

https://github.com/AlibabaResearch/AdvancedLiterateMachinery/tree/main/DocumentUnderstanding/GeoLayoutLM

**Comment by huyhoang17** [comment]
Thank you!
