### ISSUE TITLE
MagickWand错误，按照提示，不能下载

### ISSUE THREAD

**Issue by EternityWM** [AlibabaResearch/AdvancedLiterateMachinery#20]
libraries = load_library()出错

ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.

Try to install:
  apt-get install libmagickwand-dev

请问有遇到过这种问题吗？已经按照说明，也尝试了各种源，但是不能下载

**Comment by Rachel-Yang** [comment]
同问，你解决了吗·

**Comment by wdp-007** [comment]
sudo apt-get install libmagickwand-dev
