### ISSUE TITLE
Entity Grouping function for GeoLayoutLM

### ISSUE THREAD

**Issue by harshyadav17** [AlibabaResearch/AdvancedLiterateMachinery#21]
Hello team!

Thanks for such a great contribution to the open-source community. 

Can you please explain about the logic behind entity-grouping done to identify the entities before linking key-value pairs. It would be great if you can also point me to that respective function in the repo.

Thanks!

**Comment by ccx1997** [comment]
Hello, thank you for your attention to our work!

The idea of grouping entities by linking was proposed in [BROS](https://arxiv.org/abs/2108.04539) for the dataset CORD. In an entity group, you can set a specified-class entity as the father node, and other entities as son nodes. Thus the entity grouping task is converted to the relation extraction (aka entity linking) task. In this repo, we only open source the pre-processing on FUNSD.

In fact, the sub-tasks (SER, REaGRP, REaKV) can be performed without a pre-defined order. They are only technical tasks. One may convert the VIE task into the sub-tasks according to his/her demand.

**Comment by sandeepmbmkn** [comment]
@ccx1997 what your thought is if we can group words(token on SER output) of same class based on distance and group into multi-word entity recognition. Over and above of these multi entity, RE can link the appropriate key-value relationship.
