### ISSUE TITLE
LORE-TSR's TEDS metrics?

### ISSUE THREAD

**Issue by taoyao1221** [AlibabaResearch/AdvancedLiterateMachinery#22]
How does the LORE-TSR calculate TEDS indicators on the PubTabNet dataset? 
How is the blank cell situation handled?

**Comment by BrownXing** [comment]
We first change the structure represented as logical axis into HTML following a pseudo code :  
![image](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/43274427/0946d37f-eae2-4820-bc94-b247e12f07c2)
and then compute the TEDS.
