### ISSUE TITLE
Regarding the inference relation head in the GeoLayoutLM and LayoutLMv3 models

### ISSUE THREAD

**Issue by ndblong95** [AlibabaResearch/AdvancedLiterateMachinery#24]
I would like to express my gratitude for your hard work. 
Upon reviewing the benchmark table, I have observed the impressive accuracy of the relation head in GeoLayoutLM. Would it be possible for you to share the code for pre-produce the result of LayoutLMv3 or provide guidance on how to integrate it with the current source code?

**Comment by luochuwei** [comment]
@ndblong95 

Hello, thank you for your attention to our work!

- model:  initialize layoutlmv3model in the class GeoLayoutLMVIEModel (for example, replace the "self.geolayoutlm_model = GeoLayoutLMModel(self.backbone_config)" to "self.layoutlmv3model= LayoutLMv3Model.from_pretrained("layoutlmv3-model-path")")
- data preprocess: use LayoutLMv3Processor to do data preprocessing in the GeoLayoutLM/lightning_modules/data_modules/vie_dataset.py:89 (function _getitem_geo)

**Comment by ndblong95** [comment]
I wanted to take a moment to express my gratitude for the guidance you provided in answering my question. Your willingness to share your knowledge and expertise has made a significant impact on me.

Your advice was clear and concise, and I appreciate the time and effort you put into helping me understand the topic more fully. Your guidance has helped me approach the issue with greater confidence and a clearer understanding.

I am grateful for your kindness and willingness to assist a stranger. Your generosity of spirit is a testament to the kindness and compassion that still exists in the world today.

Thank you again for your help. Your guidance has truly made a difference, and I am grateful for the opportunity to learn from you.
