### ISSUE TITLE
关于GeoLayoutLM中文支持模型

### ISSUE THREAD

**Issue by 24-solar-terms** [AlibabaResearch/AdvancedLiterateMachinery#25]
非常感谢达摩院读光组的工作，GeoLayoutLM是个很棒的模型，但是这个模型使用的bert base的tokenizer，请问有预训练对中文支持的模型吗，或者未来会发布吗？
@wdp-007 @alibaba-oss @congyao 
非常感谢！

**Comment by luochuwei** [comment]
@24-solar-terms 在modelscope上有支持中英文的模型

**Comment by 24-solar-terms** [comment]
好的非常感谢！

**Comment by luochuwei** [comment]
@malichen-cv modelscope上有提供tokenizer，用的是XLMRoberta的tokenizer

**Comment by NextGuido** [comment]
@malichen-cv hello，有一个新问题。我有一批需要训练的中文数据，按照上面的说法，我现在只需要更改`tokenizer`就可以了是吗？还是说我的模型`backbone`和`model_ckpt`也同样需要去修改？
