### ISSUE TITLE
LORE's labels

### ISSUE THREAD

**Issue by TenMilesLotus** [AlibabaResearch/AdvancedLiterateMachinery#27]
Could you please tell me what's the meaning of the labels of LORE, especially the segmentation, logic_axis, area, iscrowd and ignore in annotations

**Comment by BrownXing** [comment]
hi, segmentation is the bounding box of the table cell and logic axis represents the starting column/row and ending column/row of the table cell

**Comment by TenMilesLotus** [comment]
Thanks, and what about area, iscrowd and ignore?

**Comment by BrownXing** [comment]
These attribute are not used for training, just inherited from the COCO dataset, can be removed from labels.

**Comment by TenMilesLotus** [comment]
Thanks!
