### ISSUE TITLE
LORE的loss部分

### ISSUE THREAD

**Issue by yangguangjie** [AlibabaResearch/AdvancedLiterateMachinery#28]
您好，非常抱歉打扰到您，有两个问题想向您请教一下。
1、在代码lore中没有发现论文中所提到的inner，inter loss函数。请问是我没找到，还是代码中没有公开？
2、在您公开的wtw数据集label中和下载的wtw中的lable和图像不能完全对应，能否提供你们做实验的那版本数据集。非常感谢。

**Comment by BrownXing** [comment]
You could use the vanilla loss for training currently, and it can also provide satisfactory results for application. The refactoring of the revised code for training is WIP. The WTW dataset provided in https://tianchi.aliyun.com/dataset/108587 is a revised version, and is more reasonable and cleaner.

**Comment by ejlee95** [comment]
> You could use the vanilla loss for training currently, and it can also provide satisfactory results for application. The refactoring of the revised code for training is WIP. The WTW dataset provided in https://tianchi.aliyun.com/dataset/108587 is a revised version, and is more reasonable and cleaner.

Could you upload the inter/intra-cell losses mentioned in the paper? Is the refactoring still in progress?
