### ISSUE TITLE
PubTabNet获取逻辑坐标和无线表格问题

### ISSUE THREAD

**Issue by zhaijianyang** [AlibabaResearch/AdvancedLiterateMachinery#30]
大佬你好，我有两个问题：
1.请问PubTabNet如何获取逻辑坐标呀？
2.对于无线表格，是不是无法预测空cell的逻辑坐标？后处理的话，是不是无法判断两个或多个相邻空cell到底是几个cell？

**Comment by SWHL** [comment]
第二个问题，我也遇到了。
我认为LORE算法有两个假设前提：
1. 每个cell中必须有值，没有值的话，是没有对应坐标的。
2. 不管cell是否跨行跨列，必须是某几个cell的合并得来的。
    - 这里从逻辑坐标的表示方式可以看出来`(start_row, end_row, start_column, end_column)`。
    - 可以在[魔搭在线demo上](https://www.modelscope.cn/models/damo/cv_resnet-transformer_table-structure-recognition_lore/summary)测试一下[这张图像](https://api.textin.com/open/image/download?filename=87ddf5cd379044dda116220f345a4d53)。
    - 下面是我跑的，对于正数第二行和倒数第二行，LORE不太可能正确还原。
    ![image](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/28639377/d66c4a60-adf7-4a35-a5ec-c87258e1b60f)

**Comment by BrownXing** [comment]
1. The logical axis of table cells in PubTabNet is computed from the HTML labels. Preorder Traversing the HTML sequence and compute the logical axis according to the <tr> <td> hierarchy and the row_span/column_span of <td>.
2. The logical axis is only predicted on detected cell boxes, the released model is only trained for text region detection. During post-processing, the connected unfilled grids are filled with only one cell. If you would like a more accurate recognition for empty cells, it can be helpful to add annotations of empty cells and train another detector module.
