### ISSUE TITLE
Geolayoutlm train.py issue

### ISSUE THREAD

**Issue by PriyankarSingha** [AlibabaResearch/AdvancedLiterateMachinery#33]
Hello team!

Thanks for such a great contribution to the open-source community.

But sadly I am stuck at one thing, at the end of train.py, it is thowing AttributeError: 'VIEDataModule' object has no attribute '_has_setup_TrainerFn.FITTING'. How to resolve this issue. Kindly help me.

**Code Snippet**
    if cfg.model.head in ["vie"]:
        pl_module = GeoLayoutLMVIEModule(cfg)
    else:
        raise ValueError(f"Not supported head {cfg.model.head}")

    # import ipdb;ipdb.set_trace()
    data_module = VIEDataModule(cfg, pl_module.net.tokenizer)

    trainer.fit(model = pl_module, datamodule=data_module)

**Error Snippet**
    Exception has occurred: AttributeError
    'VIEDataModule' object has no attribute '_has_setup_TrainerFn.FITTING'
      File "D:\TEST\GeoLayoutLM\train.py", line 52, in main
        trainer.fit(model = pl_module, datamodule=data_module)
      File "D:\TEST\GeoLayoutLM\train.py", line 56, in <module>
        main()
    AttributeError: 'VIEDataModule' object has no attribute '_has_setup_TrainerFn.FITTING'

**Comment by ccx1997** [comment]
Hello! Make sure you have the proper version of pytorch-lightning as in `requirements.txt`.

**Comment by PriyankarSingha** [comment]
The version of pytorch-lightning is `1.5.10`, which is exact according to `requirements.txt`

**Comment by ccx1997** [comment]
I found a same issue and its reply [here](https://github.com/Shivanandroy/simpleT5/issues/57#issuecomment-1627629504).
It seems to be raised by the Windows system.

**Comment by PriyankarSingha** [comment]
Okay, will try in Linux OS, thank you for the follow up.
