### ISSUE TITLE
about execution of MGP-STR code

### ISSUE THREAD

**Issue by jiangduwang** [AlibabaResearch/AdvancedLiterateMachinery#39]
I encountered this error while executing MGP-STR code：

ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

May I ask how to solve it? Thank you!

**Comment by wdp-007** [comment]
The code has two loading tasks: one for the pretrained deit weight and another for the pretrained tokenizers weight. If you encounter errors caused by network problems, you can try downloading the weights in advance and loading them locally.
