### ISSUE TITLE
MGP-STR：where is the impl of self.cls_token?

### ISSUE THREAD

**Issue by sheirving** [AlibabaResearch/AdvancedLiterateMachinery#4]
"cls_tokens = self.cls_token.expand(B, -1, -1)  # stole cls_tokens impl from Phil Wang, thanks", I can't find the impl of [self.cls_token](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/blob/ea244caa8483f080b4aab9f9fd7f7e13a07536a4/OCR/MGP-STR/modules/mgp_str.py#L67)

**Comment by wdp-007** [comment]
It is implemented in vision_transformer.py of the timm package, if you installed the timm package, you can see its specific implementation in vision_transformer.py:
`self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))`

**Comment by sheirving** [comment]
oh, thank you very much!
