### ISSUE TITLE
Visualize the GeoLayoutLM results?

### ISSUE THREAD

**Issue by ganesharavindh** [AlibabaResearch/AdvancedLiterateMachinery#41]
Here I used the pre-trained model from ModelScope but I don't know how to get the head outputs and visualize the text and image embedding for the respective image. Here I attached the ModelScope code for reference and [link ](https://www.modelscope.cn/models/damo/multi-modal_convnext-roberta-base_vldoc-embedding/summary)also.

```
from modelscope.models import Model
from modelscope.pipelines import pipeline

model = Model.from_pretrained('damo/multi-modal_convnext-roberta-base_vldoc-embedding')
doc_VL_emb_pipeline = pipeline(task='document-vl-embedding', model=model)

inp = {
    'images': ['data/demo.png'], 
    'ocr_info_paths': ['data/demo.json']
}
result = doc_VL_emb_pipeline(inp)

print('Results of VLDoc: ')
for k, v in result.items():
    print(f'{k}: {v.size()}')
# Expected output:
# img_embedding: torch.Size([1, 151, 768]), 151 = 1 global img feature + 150 segment features
# text_embedding: torch.Size([1, 512, 768])
```

Thanks in advance!

**Comment by ccx1997** [comment]
In modelscope, only the backbone is released. So the head is not available by now.
To use the model in modelscope, you should first [install](https://www.modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85) the environment.
