### ISSUE TITLE
关于geolayoutLM的模型输入

### ISSUE THREAD

**Issue by Jermaine1996** [AlibabaResearch/AdvancedLiterateMachinery#43]
你好，
请问下模型输入中：bbox_4p_normalized，line_rank_id，line_rank_inner_id是什么意思？

**Comment by ccx1997** [comment]
`bbox_4p_normalized` is the word boxes used in [BROS encoder](https://arxiv.org/pdf/2108.04539.pdf).
`line_rank_id` and `line_rank_inner_id` are the 1D segment rank id and 1D segment BIE id respectively (page 3 of the paper).
