### ISSUE TITLE
tokenizer问题

### ISSUE THREAD

**Issue by tonylin52** [AlibabaResearch/AdvancedLiterateMachinery#59]
按照要求安装好环境后，运行preprocess.py的时候出现问题：

OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by wdp-007** [comment]
Please make sure that you have access to the Hugging Face website and installed the correct transformer version. Alternatively, you can clone the "bert-base-uncased" repository to your local directory and then modify the line 'BertTokenizer.from_pretrained("bert-base-uncased")' to 'BertTokenizer.from_pretrained("/path/to/bert-base-uncased")'.

**Comment by tonylin52** [comment]
这个墙的问题了，先下载好后，再本地加载。

**Comment by wu-yz** [comment]
请问除了git还有别的下载方式嘛？没有找到唉
