### ISSUE TITLE
demo_imgs.py not working 

### ISSUE THREAD

**Issue by mlkorra** [AlibabaResearch/AdvancedLiterateMachinery#6]
Thank you for sharing your incredible work. I was trying to run the levocr pretrained model on couple of demo images.
demo_imgs script wasn't running, resolved it by making few changes in the demo_imgs.py

Following are the changes I have made  -

At Line 141 `model.module.load_state_dict(torch.load(opt.saved_model, map_location=device),strict=False)`
At Line 150  `AlignCollate_demo = AlignCollateTest(imgH=opt.imgH, imgW=opt.imgW)`
At Line 171   `vision_final_pred, _ = converter.encode_levt(vision_preds_str, src_dict, device=device, batch_max_length=pred_vision.size(1))`

So,when I ran the script, this was the output

![image](https://user-images.githubusercontent.com/18375776/209376352-dd7f2840-21a4-4f57-8168-0f68c5af22a4.png)

Can you help me to interpret the output or the right way to run the demo script?

**Comment by wdp-007** [comment]
It looks like you didn't load the correct model, which one are you using?

**Comment by mlkorra** [comment]
@wdp-007 Thank you for the reply. I was using LevOCR-model from the given [pretrained models](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/tree/main/OCR/LevOCR#pretrained-models)

**Comment by wdp-007** [comment]
I re-downloaded the model and it works fine in my environment
```
python3 demo_imgs.py  --imgH 32 --imgW 128  --max_iter 2 --batch_size 16 --model_dir levocr_model.pth --rgb --th 0.5 --demo_imgs demo_imgs
demo_imgs/5_BALLYS.png
Visual Prediction: bally
Iteration1:Del-Plh-Ins bally-bally<unk>-ballys
Iteration2:Del-Plh-Ins ballys-ballys-ballys
Iteration3:Del-Plh-Ins ballys-ballys-ballys
=======================================
demo_imgs/88_Celebrating.png
Visual Prediction: gelebrating
Iteration1:Del-Plh-Ins elebrating-<unk>elebrating-celebrating
Iteration2:Del-Plh-Ins celebrating-celebrating-celebrating
Iteration3:Del-Plh-Ins celebrating-celebrating-celebrating
=======================================
demo_imgs/100_MANCHESTER.png
Visual Prediction: manchlsste
Iteration1:Del-Plh-Ins manchste-manch<unk>ste<unk>-manchester
Iteration2:Del-Plh-Ins manchester-manchester-manchester
Iteration3:Del-Plh-Ins manchester-manchester-manchester
=======================================
demo_imgs/229_REGISTER.png
Visual Prediction: regester
Iteration1:Del-Plh-Ins regster-reg<unk>ster-register
Iteration2:Del-Plh-Ins register-register-register
Iteration3:Del-Plh-Ins register-register-register
=======================================
demo_imgs/276_MOTORS.png
Visual Prediction: moroes
Iteration1:Del-Plh-Ins mos-mo<unk><unk><unk>s-morors
Iteration2:Del-Plh-Ins moors-mo<unk>ors-motors
Iteration3:Del-Plh-Ins motors-motors-motors
```
Did you download this model：https://github.com/AlibabaResearch/AdvancedLiterateMachinery/releases/download/v1.0.3-LevOCR-model/levocr_model.pth？

**Comment by mlkorra** [comment]
@wdp-007 Yes,I am using the same model. Can you share the updated `demo_imgs.py`  file,I am getting errors with the current script.
Ex : At Line 171, `converter.encode_levt_tgt` doesn't exist in the utils file.

**Comment by wdp-007** [comment]
Sorry for that, I have updated the `demo_imgs.py`, you can try again.

**Comment by mlkorra** [comment]
Thanks for the updated script,it's working now @wdp-007
