### ISSUE TITLE
LORE paper supplementary materials

### ISSUE THREAD

**Issue by nghiawibu** [AlibabaResearch/AdvancedLiterateMachinery#65]
I can't find the supplementary materials anywhere in the LORE paper. Does anyone know where to find it?

**Comment by BrownXing** [comment]
Thank you for letting us know. Here is the manuscript of the supplementary materials. We will add an official version on the arXiv.
[Uploading supplementary.pdf…]()

**Comment by BrownXing** [comment]
[supplementary.pdf](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/files/13316434/supplementary.pdf)
