### ISSUE TITLE
Problem with text layout detection

### ISSUE THREAD

**Issue by light42** [AlibabaResearch/AdvancedLiterateMachinery#69]
I faced problem where docxlayout can't detect text layout when it overlapped/near figure layout. The case I'm concerned about is when handling document signatures, most of the time text could be overlapped with hand-written signs/stamps.

What I want is for the model to ignore those figures and only detect the texts. Is there a way to fix that? I've tried to modify parameters from opts.py to no avail.

**Comment by congyao** [comment]
> I faced problem where docxlayout can't detect text layout when it overlapped/near figure layout. The case I'm concerned about is when handling document signatures, most of the time text could be overlapped with hand-written signs/stamps.
> 
> What I want is for the model to ignore those figures and only detect the texts. Is there a way to fix that? I've tried to modify parameters from opts.py to no avail.

Thanks!

Since the code and examplar model of DocXLayout are released, you can add new data, modify the settings and re-train the model to solve the problems you have encountered.
