### ISSUE TITLE
Some error about MGP-STR

### ISSUE THREAD

**Issue by wu-yz** [AlibabaResearch/AdvancedLiterateMachinery#78]
When I try to run demo.py, I meet this error:
OSError: Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2Tokenizer tokenizer.

**Comment by wdp-007** [comment]
Please refer to this issue:[issue59](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/issues/59)
