### ISSUE TITLE
新思路：文档通用理解

### ISSUE THREAD

**Issue by tianchiguaixia** [AlibabaResearch/AdvancedLiterateMachinery#79]
主要介绍一下，使用大模型在各种图片上的抽取案例。

1.支持所有图片类型，无需训练  
2.支持交互，所答即所见
3.适配换行的文本，换行也能结构化   
4.返回坐标信息 ，并在图片上打上对应框选位置    
5.自定义化的功能，本体的定义，fewshot学习，各种大模型切换等等。

**Comment by tianchiguaixia** [comment]
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/29837553/6db2b2e7-f5c5-4baf-9a64-a6e930f78eab

**Comment by tianchiguaixia** [comment]
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/29837553/417eacb7-3c47-47d6-b46a-a9546b02ec07

**Comment by tianchiguaixia** [comment]
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/29837553/c0ef61a1-53db-4bb4-aecf-b2d5a0997417

**Comment by tianchiguaixia** [comment]
https://github.com/AlibabaResearch/AdvancedLiterateMachinery/assets/29837553/4b07f547-f7a6-4440-b013-7f32bc0df6bf

**Comment by 804782069** [comment]
> 主要介绍一下，使用大模型在各种图片上的抽取案例。
> 
> 1.支持所有图片类型，无需训练 2.支持交互，所答即所见 3.适配换行的文本，换行也能结构化 4.返回坐标信息 ，并在图片上打上对应框选位置 5.自定义化的功能，本体的定义，fewshot学习，各种大模型切换等等。

大佬，有能运行的代码吗？学习一下，谢谢

**Comment by hwb96** [comment]
会开源吗大佬

**Comment by tianchiguaixia** [comment]
会的
