### ISSUE TITLE
MJ和ST数据集图片是灰白的吗？image的channel为1啊。

### ISSUE THREAD

**Issue by 67766767** [AlibabaResearch/AdvancedLiterateMachinery#8]

**Comment by wdp-007** [comment]
是基于RGB的，image的channel默认为3，具体可以参看utils中的`--input_channel`参数。

**Comment by 67766767** [comment]
但是在执行 x = self.patch_embed(x) 的时候，出现 RuntimeError: Given groups=1, weight of size [768, 3, 4, 4], expected input[192, 1, 32, 128] to have 3 channels, but got 1 channels instead。而且我查看 get_batch 返回的image形状为[192, 1, 32, 128],这是为什么呢？

**Comment by wdp-007** [comment]
请问你是运行的哪个模型的哪个脚本？方便把你的运行代码贴出来吗？

**Comment by 67766767** [comment]
我仔细看了一下，应该是没有指定 --rgb，指定后正常，返回的image形状为[192, 3, 32, 128]。感谢回复。
