### ISSUE TITLE
MGP-STR

### ISSUE THREAD

**Issue by wu-yz** [AlibabaResearch/AdvancedLiterateMachinery#80]
请问MGP-STR中的A3实现部分在哪里呀？论文有点看不明白，就去看了代码，没找着对应的模块，可以指路一下嘛！

**Comment by wdp-007** [comment]
Please refer to this link: [token_leaner](https://github.com/AlibabaResearch/AdvancedLiterateMachinery/blob/main/OCR/MGP-STR/modules/token_learner.py)
