### ISSUE TITLE
Paper link of LORE-TSR

### ISSUE THREAD

**Issue by YanShuang17** [AlibabaResearch/AdvancedLiterateMachinery#9]
Hi Authors,  Could you please provide the paper  dpf link of LORE-TSR ? Thanks !

**Comment by BrownXing** [comment]
This is the ArXiv version of LORE-TSR: https://arxiv.org/abs/2303.03730. Thank you for reminding us!

**Comment by BrownXing** [comment]
This is the ArXiv version of LORE-TSR: https://arxiv.org/abs/2303.03730. Thank you for reminding us!

**Comment by YanShuang17** [comment]
Thanks a lot !
